language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"


script:
 # Build: docker build -t <optional: image name> <Dockerfile path>
 - docker build -t udagram-api-feed ./udagram-api-feed
 - docker build -t udagram-api-user ./udagram-api-user
 - docker build -t udagram-frontend ./udagram-frontend
 - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tag a local image with ID <Image ID> into the “mohamedghanem”'s repository "udagram-*" with “v1”
 - docker tag udagram-api-feed mohamedghanem/udagram-api-feed:v1
 - docker tag udagram-api-user mohamedghanem/udagram-api-user:v1
 - docker tag udagram-frontend mohamedghanem/udagram-frontend:v2
 - docker tag udagram-reverseproxy mohamedghanem/udagram-reverseproxy:v1

after_success:
 # Retrieve Credentials from Travis Environment Variables to be able to push
 - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
 # Push
 - docker push mohamedghanem/udagram-api-feed:v1
 - docker push mohamedghanem/udagram-api-user:v1
 - docker push mohamedghanem/udagram-frontend:v2
 - docker push mohamedghanem/udagram-reverseproxy:v1